### PR TITLE
Obask 633 react js

### PR DESCRIPTION
**Pull request by ollie64**
still need build script to run react UI

### CODE REVIEW

**Comment by manuel** [comment]
- ReactServlet duplicates most UIServlet code?
- Parsing URL should probably use a library like https://github.com/medialize/URI.js
- What are the static JSON files in assets/ for?

**Comment by ollie64** [comment]
Assets files needs to write rendering code separate from java controllers
I.e. you can open index.html#test from file system and it will use assets instead of requesting JSON from server.

**Comment by ollie64** [comment]
Some notes from HipChat
[4:44 AM] Manuel Simoni: zooming seems very slow
[4:46 AM] Manuel Simoni: unlisted workflows should be sorted alphabeticaly
[4:47 AM] Manuel Simoni: prev page doesn't really go one page back
[4:50 AM] Manuel Simoni: and of course, the direction of time is wrong :)
[4:52 AM] Manuel Simoni: the wait,fail,rdy, etc labels should be displayed
[4:54 AM] Manuel Simoni: the gc-batchimport-multiscreen workflow is not displayed as missing

**Comment by ollie64** [comment]
This branch was merged into obask-ui-merge-easy

**Pull request closed without merging**
